name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # The project currently does not compile on Windows. This is due to
          # * sys/time.h usage
          # * Non-compile time C-array sizes
          # * Potentially many more reasons.exclude:
          # TODO: Discuss with Luca how important Windows support would be for community acceptance.
          # - windows-latest
        python-version: ["3.10", "3.13"]

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python package
      run: |
        python -m pip install .[tests]

    - name: Run pytest
      run: |
        python -m pytest
