name: Build Wheels + PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      deploy_to_testpypi:
        description: "Whether the build should be deployed to test.pypi.org"
        required: true
        default: "false"


jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # see comment in ci.yml
          # - windows-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.2.0

    - uses: actions/upload-artifact@v4
      with:
        path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build-wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.13.0

  upload_testpypi:
    needs: [build-wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event.inputs.deploy_to_testpypi == 'true'

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
